### ISSUE TITLE
Unexpected Exception at line 83 of funnel.py (master)

### ISSUE THREAD

**Issue by vardaofthevalier** [bmeg/funnel#4]
Here is the traceback of the exception that I get when I run the command `python funnel.py --gce gce_config.yaml test/hashsplitter-workflow.cwl --input gs://<gcs-object-path>`:

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/workflow.py", line 530, in job
    **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/draft2tool.py", line 262, in job
    builder.pathmapper = self.makePathMapper(reffiles, builder.stagedir, **make_path_mapper_kwargs)
  File "funnel.py", line 332, in makePathMapper
    return GCEPathMapper(reffiles, self.pipeline.config['bucket'], self.pipeline.config['output-path'])
  File "funnel.py", line 83, in __init__
    if src.startswith('gs://'):
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by prismofeverything** [comment]
This is fixed. The correct invocation is:

```
python -m funnel.main --gce gce_config.yaml test/hashsplitter-workflow.cwl --input gs://<gcs-object-path>
```
